[workspace]
members = [
    "protocol",
    "server",
    "client",
]
resolver = "2"  # свежий алгоритм feature‑unification

# === workspace‑wide version overrides ===
[workspace.dependencies]
windows      = "0.58.0"
windows-core = "0.58.0"
windows-sys  = "0.58.0"