[package]
name = "server"
edition = "2024"
version = "0.1.0"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
bevy = { version = "0.18", default-features = false, features = ["bevy_asset", "bevy_render", "bevy_sprite"] }
bevy_window = "0.18"
bevy_quinnet = { version = "0.20.0", features = ["bincode-messages"] }
protocol = { path = "../protocol", features = ["quinnet"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[dev-dependencies]
bevy = { version = "0.18", default-features = false }
protocol = { path = "../protocol" }